namespace boredBets.Models
{
    public class FilePathConstants
    {
        //public static readonly string StaticData = Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "..", "..", "..", "staticData");



        // Common files
        //public static readonly string FamilyNames = Path.Combine(StaticData, "familyNames.txt");
        public static readonly List<string> FamilyNames = new List<string>
    {
        "Adams",
        "Alexander",
        "Allen",
        "Anderson",
        "Andrews",
        "Armstrong",
        "Atkinson",
        "Bailey",
        "Baker",
        "Ball",
        "Barker",
        "Barnes",
        "Barnett",
        "Barron",
        "Barton",
        "Bass",
        "Bauer",
        "Bell",
        "Bennett",
        "Bentley",
        "Berry",
        "Bishop",
        "Blevins",
        "Booth",
        "Bradley",
        "Bridges",
        "Brock",
        "Brooks",
        "Brown",
        "Browne",
        "Browning",
        "Bryant",
        "Buchanan",
        "Buckley",
        "Buckner",
        "Bullock",
        "Burton",
        "Butler",
        "Campbell",
        "Carter",
        "Chapman",
        "Clark",
        "Clarke",
        "Cole",
        "Coleman",
        "Collins",
        "Cook",
        "Cooke",
        "Cooper",
        "Cox",
        "Davies",
        "Davis",
        "Dawson",
        "Day",
        "Dixon",
        "Douglas",
        "Edwards",
        "Ellis",
        "Evans",
        "Fisher",
        "Fitzgerald",
        "Fletcher",
        "Ford",
        "Foster",
        "Fox",
        "Freeman",
        "Gardner",
        "Gibson",
        "Gordon",
        "Graham",
        "Grant",
        "Gray",
        "Green",
        "Hall",
        "Hamilton",
        "Harris",
        "Harris",
        "Harrison",
        "Hart",
        "Harvey",
        "Hawkins",
        "Hawthorne",
        "Henderson",
        "Hensley",
        "Hess",
        "Hickman",
        "Higgins",
        "Hill",
        "Hobbs",
        "Hodge",
        "Hodge",
        "Holland",
        "Hollis",
        "Holmes",
        "Holt",
        "Hood",
        "Horton",
        "Howard",
        "Hudson",
        "Huffman",
        "Hughes",
        "Humphrey",
        "Hunt",
        "Hunter",
        "Hutchinson",
        "Jackson",
        "James",
        "Johnson",
        "Johnston",
        "Jones",
        "Kelly",
        "Kennedy",
        "King",
        "Knight",
        "Lane",
        "Lawrence",
        "Lee",
        "Lewis",
        "Long",
        "Marshall",
        "Martin",
        "Mason",
        "Matthews",
        "McDonald",
        "Miller",
        "Mills",
        "Mitchell",
        "Moore",
        "Morgan",
        "Morris",
        "Morrison",
        "Murphy",
        "Murray",
        "Nelson",
        "Newton",
        "Page",
        "Palmer",
        "Parker",
        "Payne",
        "Pearson",
        "Perry",
        "Phillips",
        "Porter",
        "Powell",
        "Price",
        "Reed",
        "Reid",
        "Reynolds",
        "Richards",
        "Richardson",
        "Roberts",
        "Robertson",
        "Robinson",
        "Rogers",
        "Rose",
        "Ross",
        "Russell",
        "Ryan",
        "Scott",
        "Shaw",
        "Simpson",
        "Sleyter",
        "Sloligh",
        "Slomski",
        "Slusch",
        "Smallwoode",
        "Smidth",
        "Smith",
        "Spencer",
        "Stevens",
        "Stewart",
        "Stone",
        "Sullivan",
        "Sutton",
        "Taylor",
        "Thomas",
        "Thompson",
        "Thomson",
        "Todd",
        "Turner",
        "Walker",
        "Wallace",
        "Walsh",
        "Ward",
        "Warren",
        "Watson",
        "Webb",
        "Webster",
        "Wells",
        "West",
        "Wheeler",
        "White",
        "Wilkinson",
        "Williams",
        "Williamson",
        "Wilson",
        "Wood",
        "Woods",
        "Wright",
        "Young"
    };
        //public static readonly string MaleNames = Path.Combine(StaticData, "maleNames.txt");
        public static readonly List<string> MaleNames = new List<string> {
            "Aaron", "Adam", "Alan", "Albert", "Alexander", "Andrew", "Anthony", "Arthur", "Austin", "Benjamin",
            "Billy", "Bobby", "Bradley", "Brandon", "Brian", "Bruce", "Bryan", "Carl", "Charles", "Chris",
            "Christian", "Christopher", "Craig", "Daniel", "David", "Dennis", "Donald", "Douglas", "Edward",
            "Eric", "Ethan", "Frank", "Frederick", "Gary", "George", "Gerald", "Gregory", "Henry", "Howard",
            "Jack", "Jacob", "James", "Jason", "Jeffrey", "Jeremy", "Jerry", "Joe", "John", "Johnny",
            "Jonathan", "Jordan", "Jose", "Joseph", "Joshua", "Justin", "Keith", "Kenneth", "Kevin", "Kyle",
            "Larry", "Lawrence", "Lee", "Louis", "Luis", "Mark", "Matthew", "Michael", "Nathan", "Nicholas",
            "Noah", "Patrick", "Paul", "Peter", "Philip", "Randy", "Raymond", "Richard", "Robert", "Roger",
            "Ronald", "Russell", "Ryan", "Sam", "Samuel", "Scott", "Sean", "Shawn", "Stephen", "Steven",
            "Terry", "Thomas", "Timothy", "Todd", "Travis", "Tyler", "Vincent", "Walter", "William", "Willie",
            "Zachary"
        };
        //public static readonly string FemaleNames = Path.Combine(StaticData, "femaleNames.txt");
        public static readonly List<string> FemaleNames = new List<string> {
        "Abigail", "Addison", "Adeline", "Alice", "Allison", "Amelia", "Anna", "Aria", "Ariana", "Athena",
        "Aubrey", "Audrey", "Aurora", "Autumn", "Ava", "Avery", "Ayla", "Bella", "Brooklyn", "Camila",
        "Caroline", "Charlotte", "Chloe", "Claire", "Cora", "Delilah", "Eleanor", "Elena", "Eliana",
        "Elizabeth", "Ella", "Ellie", "Eloise", "Emery", "Emilia", "Emily", "Emma", "Evelyn", "Everleigh",
        "Everly", "Gabriella", "Genesis", "Gianna", "Grace", "Hailey", "Hannah", "Harper", "Hazel", "Iris",
        "Isabella", "Isla", "Ivy", "Jade", "Josephine", "Kennedy", "Kinsley", "Layla", "Leah", "Leilani",
        "Liliana", "Lillian", "Lily", "Lucy", "Luna", "Lydia", "Madelyn", "Madison", "Maria", "Maya",
        "Mia", "Mila", "Naomi", "Natalia", "Natalie", "Nevaeh", "Nora", "Nova", "Olivia", "Paisley",
        "Penelope", "Quinn", "Raelynn", "Riley", "Ruby", "Sadie", "Sarah", "Savannah", "Scarlett",
        "Serenity", "Skylar", "Sofia", "Sophia", "Sophie", "Stella", "Valentina", "Victoria", "Violet",
        "Willow", "Zoe", "Zoey"
    };
        //public static readonly string MaleMiddleNames = Path.Combine(StaticData, "maleMiddleNames.txt");
        public static readonly List<string> MaleMiddleNames = new List<string> {
        "Aaron", "Adam", "Alex", "Asher", "Axel", "Blake", "Cade", "Caleb", "Chase", "Clay",
        "Cole", "Dean", "Drew", "Eli", "Ethan", "Evan", "Ezra", "Felix", "Finn", "Ian",
        "Jace", "Jude", "Kai", "Lark", "Walker"
    };
        //public static readonly string FemaleMiddleNames = Path.Combine(StaticData, "femaleMiddleNames.txt");
        public static readonly List<string> FemaleMiddleNames = new List<string> {
        "Maeve", "Alice", "Mae", "Jane", "Elizabeth", "Grace", "Avalon", "Dot", "Heaven", "Justice",
        "India", "June", "Kennedy", "Mercy", "Nova", "Pearl", "Tess", "Adele", "Belle", "Blair",
        "Bree", "Brooke", "Caprice", "Cerise", "Alice"
    };
        //public static readonly string Countries = Path.Combine(StaticData, "countries.txt");
        public static readonly List<string> Countries = new List<string> {
        "Afghanistan", "Albania", "Algeria", "Andorra", "Angola", "Antigua and Barbuda", "Argentina",
        "Armenia", "Australia", "Austria", "Azerbaijan", "Bahamas", "Bahrain", "Bangladesh", "Barbados",
        "Belarus", "Belgium", "Belize", "Benin", "Bhutan", "Bolivia", "Bosnia and Herzegovina", "Botswana",
        "Brazil", "Brunei", "Bulgaria", "Burkina Faso", "Burundi", "Cabo Verde", "Cambodia", "Cameroon",
        "Canada", "Central African Republic", "Chad", "Chile", "China", "Colombia", "Comoros", "Congo",
        "Costa Rica", "Côte d'Ivoire", "Croatia", "Cuba", "Cyprus", "Czechia", "Democratic Republic of the Congo",
        "Denmark", "Djibouti", "Dominica", "Dominican Republic", "Ecuador", "Egypt", "El Salvador",
        "Equatorial Guinea", "Eritrea", "Estonia", "Eswatini", "Ethiopia", "Fiji", "Finland", "France",
        "Gabon", "Gambia", "Georgia", "Germany", "Ghana", "Greece", "Grenada", "Guatemala", "Guinea",
        "Guinea-Bissau", "Guyana", "Haiti", "Honduras", "Hungary", "Iceland", "India", "Indonesia", "Iran",
        "Iraq", "Ireland", "Israel", "Italy", "Jamaica", "Japan", "Jordan", "Kazakhstan", "Kenya", "Kiribati",
        "Kuwait", "Kyrgyzstan", "Laos", "Latvia", "Lebanon", "Lesotho", "Liberia", "Libya", "Liechtenstein",
        "Lithuania", "Luxembourg", "Madagascar", "Malawi", "Malaysia", "Maldives", "Mali", "Malta",
        "Marshall Islands", "Mauritania", "Mauritius", "Mexico", "Micronesia", "Moldova", "Monaco",
        "Mongolia", "Montenegro", "Morocco", "Mozambique", "Myanmar", "Namibia", "Nauru", "Nepal",
        "Netherlands", "New Zealand", "Nicaragua", "Niger", "Nigeria", "North Korea", "North Macedonia",
        "Norway", "Oman", "Pakistan", "Palau", "Palestine State", "Panama", "Papua New Guinea", "Paraguay",
        "Peru", "Philippines", "Poland", "Portugal", "Qatar", "Romania", "Russia", "Rwanda",
        "Saint Kitts and Nevis", "Saint Lucia", "Saint Vincent and the Grenadines", "Samoa", "San Marino",
        "Sao Tome and Principe", "Saudi Arabia", "Senegal", "Serbia", "Seychelles", "Sierra Leone",
        "Singapore", "Slovakia", "Slovenia", "Solomon Islands", "Somalia", "South Africa", "South Korea",
        "South Sudan", "Spain", "Sri Lanka", "Sudan", "Suriname", "Sweden", "Switzerland", "Syria",
        "Tajikistan", "Tanzania", "Thailand", "Timor-Leste", "Togo", "Tonga", "Trinidad and Tobago",
        "Tunisia", "Turkey", "Turkmenistan", "Tuvalu", "Uganda", "Ukraine", "United Arab Emirates",
        "United Kingdom", "United States of America", "Uruguay", "Uzbekistan", "Vanuatu", "Venezuela",
        "Vietnam", "Yemen", "Zambia", "Zimbabwe"
    };

        // Specific files
        //public static readonly string Tracks = Path.Combine(StaticData, "trackNames.txt");
        //public static readonly string MaleHorses = Path.Combine(StaticData, "maleHorses.txt");
        public static readonly List<string> MaleHorses = new List<string> {
        "Abe", "Amigo", "Amos", "Apollo", "Applejack", "Arnold", "Austin", "Bailey", "Bandit", "Barnabus",
        "Barry", "Beamer", "Bear", "Billy", "Blackjack", "Blaze", "Bourbon", "Breeze", "Buck", "Butterscotch",
        "Cadet", "Cadet", "Calvin", "Campinto", "Campinto", "Card Shark", "Cash", "Cecil", "Century", "Century",
        "Charger", "Charger", "Chewy", "Chilly", "Chilly", "Cisco", "Cisco", "Claude", "Cody", "Comet", "Comet",
        "Copper", "Cornelius", "Cowboy", "Creole", "Creole Man", "Cricket", "Cricket Star", "Cuba", "Cuba",
        "Cupid", "Cyclops", "Cyclops", "Damien", "Damien", "Dandy", "Dante", "Danny", "Dave", "Defiant",
        "Defiant", "Deputy", "Dexter", "Dexter", "Dusty", "Dusty", "Dusty Road", "Echo", "Echo", "Eclipse",
        "Edwin", "Elk", "Elk", "Elzar", "Elzar", "Flame", "Flame", "Flash", "Flash", "Fleet", "Fleet Ranger",
        "Franklin", "Franklin", "Frederick", "George", "Ghost", "Gizmo", "Gizmo", "Godfather", "Green Arrow",
        "Gulliver", "Gulliver", "Hans", "Hans", "Harvey", "Hawk", "Hawk", "Hercules", "Hero", "Howard",
        "Hunter", "Hunter", "Huntsmoor", "Huntsmoor", "Ichabod", "Ichabod", "Jack", "Jimmy", "Jingles",
        "Jingles", "Jocky", "Jocky", "Johnny", "Joker", "Joker", "Julian", "Junior", "Junior", "Justin",
        "Kangaroo", "Kangaroo", "Klingon", "Klingon", "Legacy", "Mercedes", "Midnight", "Mocha", "Murphy",
        "Neville", "Orville", "Outlaw", "Patrick", "Patriot", "Pepper", "Peter", "Phantom", "Phineas",
        "Pirate", "Poncho", "Preston", "Rascal", "Rebel", "Rocky", "Shadow", "Shark", "Sheriff", "Snickers",
        "Spot", "Star", "Starlight", "Storm", "Teddy", "Tequila", "Tex", "Thaddeus", "Thunder", "Trooper",
        "Turner", "Vergil", "Walter", "Whiskey", "Whisper", "Winston", "Wrangler", "Yankee"
    };
        //public static readonly string FemaleHorses = Path.Combine(StaticData, "femaleHorses.txt");
        public static readonly List<string> FemaleHorses = new List<string> {
        "Adella", "Alaska", "Amber", "Annabelle", "Arizona", "Athena", "Aurora", "Autumn", "Barbie",
        "Beauty", "Bella", "Belle", "Blondie", "Blossom", "Bluebell", "Bonnie", "Brandy", "Briana",
        "Brooke", "Calliope", "Camilla", "Celeste", "China", "Clara", "Cleo", "Clover", "Dahlia",
        "Daisy", "Dakota", "Daphne", "Dawn", "Delilah", "Ebony", "Eclipse", "Eden", "Elfin", "Elise",
        "Eloisa", "Ember", "Esmeralda", "Estrella", "Eve", "Fantasia", "Fawn", "Felicity", "Fern",
        "Fiona", "Flora", "Freya", "Frida", "Gemini", "Giselle", "Gypsy", "Hazel", "Helena", "Honey",
        "Hyacinth", "India", "Indiana", "Ivory", "Josephine", "Juliette", "Kalli", "Kenya", "Kira",
        "Lavinia", "Lilly", "Lucinda", "Magnolia", "Maple", "Marble", "Marigold", "Millie", "Misty",
        "Montana", "Natalia", "Nevada", "Nova", "Octavia", "Paris", "Penelope", "Petunia", "Poppy",
        "Rose", "Rosie", "Sabrina", "Sierra", "Sky", "Star", "Starlight", "Stella", "Sunny", "Trinity",
        "Valentina", "Velvet", "Veronica", "Violet", "Willow", "Zara", "Zoe"
    };
        //public static readonly string HorseFirst = Path.Combine(StaticData, "horseFirst.txt");
        public static readonly List<string> HorseFirst = new List<string> {
        "attractive", "bald", "beautiful", "chubby", "clean", "dazzling", "elegant", "fancy", "fit",
        "flabby", "glamorous", "gorgeous", "handsome", "long", "magnificent", "muscular", "plain",
        "plump", "quaint", "scruffy", "short", "skinny", "ugly", "unkempt", "ashy", "black", "blue",
        "gray", "green", "icy", "lemon", "mango", "orange", "purple", "red", "salmon", "white", "yellow",
        "alive", "careful", "clever", "easy", "famous", "gifted", "helpful", "important", "inexpensive",
        "mealy", "mushy", "odd", "poor", "powerful", "rich", "shy", "tender", "vast", "aggressive",
        "ambitious", "brave", "calm", "delightful", "eager", "faithful", "gentle", "happy", "jolly",
        "kind", "lively", "nice", "obedient", "polite", "proud", "silly", "victorious", "witty",
        "wonderful", "zealous", "angry", "bewildered", "clumsy", "embarrassed", "fierce", "grumpy",
        "itchy", "jealous", "lazy", "mysterious", "nervous", "obnoxious", "panicky", "pitiful",
        "repulsive", "scary", "thoughtless", "uptight", "worried", "broad", "crooked", "curved", "deep",
        "flat", "high", "hollow", "low", "narrow", "refined", "round", "shallow", "square", "steep",
        "straight", "wide", "big", "colossal", "gigantic", "great", "huge", "immense", "large", "little",
        "mammoth", "massive", "microscopic", "miniature", "puny", "scrawny", "small", "tall", "teeny",
        "tiny", "acidic", "bitter", "cool", "creamy", "disgusting", "fresh", "juicy", "hot", "putrid",
        "rancid", "ripe", "rotten", "salty", "savory", "sour", "spicy", "spoiled", "stale", "sweet",
        "tangy", "tart", "tasteless", "tasty", "yummy", "breezy", "bumpy", "chilly", "cold", "cuddly",
        "damaged", "damp", "dirty", "dry", "flaky", "fluffy", "freezing", "greasy", "loose", "melted",
        "prickly", "rough", "shaggy", "sharp", "slimy", "sticky", "strong", "tight", "uneven", "warm",
        "weak", "wet", "wooden", "Tiny", "Shiny", "Soft", "Fuzzy", "Playful", "Silky", "Mysterious",
        "Curious", "Elegant", "Rustic", "Sleek", "Dainty", "Sweet", "Fluffy", "Delicate", "Spicy", "Fiery",
        "Charming", "Peppered", "Icy", "Glittering", "Cozy", "Chocolate", "Bubbly", "Smooth", "Cinnamon",
        "Puddle", "Truffle", "Comet", "Snickers", "Fluffy", "Dappled", "Nutty", "Creamy", "Sprinkled",
        "Dusty", "Rusty", "Pearly", "Dusky", "Sapphire", "Vibrant", "Whistling", "Shimmering", "Breezy",
        "Whiskered", "Dapper", "Quirky", "Adorable", "Snug", "Furry", "Cuddly", "Squiggly", "Zigzag",
        "Wiggly", "Dimpled", "Silken", "Tousled", "Spry", "Snappy", "Velvety", "Glossy", "Glimmering",
        "Polished", "Lively", "Flickering", "Gleaming", "Pouncing", "Plush", "Giggly", "Slinky", "Swirling",
        "Dizzy", "Snuggly", "Blinking", "Purring", "Fluttering", "Cooing", "Gurgling", "Bouncing", "Soaring",
        "Skittering", "Buzzing", "Gliding", "Glimpsing", "Swishing", "Twirling", "Skipping", "Chirping",
        "Glowing", "Crinkly", "Prickly", "Zesty", "Glistening", "Sparkling", "Perky", "Snazzy", "Posh",
        "Stylish", "Swanky", "Trendy", "Chic", "Lavish", "Opulent", "Plush", "Snug", "Comfy", "Cozy",
        "Soft", "Cushy", "Warm", "Snuggly", "Inviting", "Nuzzly", "Puffy", "Cuddly", "Huggable", "Snuggly",
        "Spongy", "Bouncy", "Squishy", "Pliable", "Floppy", "Plump", "Squeezable", "Yummy", "Squishable",
        "Cuddle", "Squeaky", "Pliable", "Puffy", "Radiant", "Shimmering", "Gleaming", "Dazzling", "Glowing",
        "Sparkling", "Glimmering", "Twinkling", "Beaming", "Glittering", "Luminous", "Brilliant", "Vivid",
        "Resplendent", "Scintillating", "Glistering", "Glossy", "Satiny", "Lustrous", "Lucid", "Incandescent",
        "Shiny", "Smooth", "Sleek", "Silken", "Velvet", "Polished", "Slick", "Silky", "Shiny", "Lustrous",
        "Satin", "Gleaming", "Radiant", "Sparkling", "Glittery", "Shimmering", "Twinkling", "Glistening",
        "Resplendent", "Glistering", "Dazzling", "Beaming", "Luminous", "Brilliant", "Vivid", "Scintillating",
        "Glimmering", "Glossy", "Satiny", "Lucid", "Incandescent", "Glossy", "Sleek", "Silken", "Velvet",
        "Polished", "Slick", "Silky", "Shiny", "Smooth", "Lustrous", "Glossy", "Satin", "Gleaming", "Radiant",
        "Sparkling", "Glittery", "Shimmering", "Twinkling", "Glistening", "Resplendent", "Glistering", "Dazzling",
        "Beaming", "Luminous", "Brilliant", "Vivid", "Scintillating", "Glimmering", "Glossy", "Satiny", "Lucid",
        "Incandescent", "Smooth", "Silken", "Sleek", "Velvet", "Polished", "Slick", "Silky", "Shiny", "Glossy",
        "Lustrous", "Satin", "Gleaming", "Radiant", "Sparkling", "Glittery"
    };
        //public static readonly string HorseSecond = Path.Combine(StaticData, "horseSecond.txt");
        public static readonly List<string> HorseSecond = new List<string>()
    {
        "Mug", "Notebook", "Sunglasses", "Backpack", "Wallet", "Headphones", "Umbrella",
        "Charger", "Bottle", "Keychain", "Pen", "T-shirt", "Sneakers", "Jeans", "Jacket",
        "Hairbrush", "Toothbrush", "Soap", "Towel", "Pillow", "Blanket", "Lamp", "Remote",
        "Laptop", "Mousepad", "Mouse", "Organizer", "Pot", "Clock", "Calendar", "Notes",
        "Stapler", "Tape", "Scissors", "Glue", "Highlighter", "Calculator", "Ruler",
        "Sharpener", "Clips", "Bands", "Whiteboard", "Marker", "Sunglasses", "Wallet", "Bag",
        "Headphones", "Book", "Magazine", "Newspaper", "Journal", "Flashlight", "Matches",
        "Lighter", "Knife", "Compass", "Kit", "Sunscreen", "Spray", "Hat", "Scarf", "Gloves",
        "Socks", "Watch", "Bracelet", "Necklace", "Earrings", "Belt", "Tie", "Wallet",
        "Sanitizer", "Balm", "Perfume", "Clip", "Clippers", "Tweezers", "Mirror", "Toothpaste",
        "Mouthwash", "Floss", "Shampoo", "Conditioner", "Wash", "Lotion", "Deodorant", "Razor",
        "Cream", "Comb", "Gel", "Spray", "Bag", "Brushes", "Mascara", "Thunderhoof", "Stardust",
        "Midnight Mirage", "Sunfire", "Shadowdance", "Whisperwind", "Frostfire", "Blazeheart",
        "Moonbeam", "Swiftstride", "Silvermane", "Amberblaze", "Stormcaller", "Dreamwalker",
        "Willowisp", "Emberstorm", "Duskrunner", "Oceanbreeze", "Starlight", "Firefly", "Mistral",
        "Nightshade", "Wildheart", "Velvetwind", "Phoenix", "Sunburst", "Frostbite", "Sapphire",
        "Thunderbolt", "Dawnstar", "Thunderhoof", "Ravenwing", "Moonshadow", "Flamestreak", "Blaze",
        "Starshine", "Whisper", "Frostwind", "Swiftwind", "Shadowfax", "Goldenhoof", "Riverdance",
        "Stormbringer", "Dreamchaser", "Twilight", "Ember", "Duskfire", "Spirit", "Silverstreak",
        "Skyfall", "Windwalker", "Firestorm", "Moonstrider", "Stormcloud", "Nightfall", "Wildfire",
        "Silvermoon", "Blazeheart", "Sapphire", "Thunderheart", "Frostfire", "Sunbeam", "Shadowdancer",
        "Whisperwind", "Starlight", "Swiftstride", "Firefly", "Mistral", "Stormcaller", "Moonbeam",
        "Emberstorm", "Willowisp", "Duskrunner", "Oceanbreeze", "Sunfire", "Frostbite", "Stardust",
        "Midnight Mirage", "Blaze", "Dreamwalker", "Thunderbolt", "Ravenwing", "Moonshadow",
        "Flamestreak", "Starshine", "Whisper", "Frostwind", "Swiftwind", "Shadowfax", "Riverdance",
        "Stormbringer", "Dreamchaser", "Twilight", "Ember", "Duskfire", "Spirit", "Silverstreak",
        "Skyfall", "Windwalker", "Firestorm", "Pebble", "Button", "Bolt", "Twig", "Marble",
        "Pearl", "Pebble", "Ribbon", "Spark", "Rusty", "Shadow", "Ember", "Copper", "Biscuit",
        "Cocoa", "Fudge", "Puddle", "Jelly", "Muffin", "Maple", "Bubble", "Oreo", "Pickle",
        "Cinnamon", "Sable", "Sage", "Whisker", "Cloud", "Taffy", "Clover", "Paws", "Velvet",
        "Dapple", "Sprout", "Maple", "Pepper", "Snickers", "Ginger", "Pebbles", "Rust", "Bubbles",
        "Marsh", "Slate", "Fluff", "Noodle", "Coal", "Caramel", "Breeze", "Sprinkle", "Snickers",
        "Pippin", "Dusk", "Frost", "Twix", "Toffee", "Puff", "Dusty", "Nutmeg", "Frosty",
        "Biscuit", "Comet", "Frost", "Sandy", "Marshmallow", "Pecan", "Twiggy", "Mocha",
        "Sprig", "Tinsel", "Pebble", "Willow", "Frost", "Ribbon", "Truffle", "Cashew", "Sable",
        "Twinkle", "Sprout", "Peaches", "Truffle", "Fudge", "Frost", "Cider", "Snickers",
        "Nutmeg", "Poppy", "Breeze", "Mocha", "Poppy", "Snickers", "Dusk", "Sprout", "Nutmeg",
        "Sprinkle", "Marshmallow", "Paws", "Ribbon", "Dapple", "Poppy", "Dusk", "Rusty",
        "Sable", "Shadow", "Spark", "Spice", "Paws", "Whisker", "Clover", "Pebble", "Velvet",
        "Twig", "Cloud", "Maple", "Breeze", "Pebble", "Cinnamon", "Bubbles", "Muffin", "Ember",
        "Toffee", "Pebble", "Biscuit", "Sprout", "Rust", "Snickers", "Pearl", "Dapple",
        "Marble", "Puddle", "Pebbles", "Nutmeg", "Sable", "Tinsel", "Twinkle", "Ribbon",
        "Pecan", "Truffle", "Marshmallow", "Snickers", "Noodle", "Jelly", "Fudge", "Sprinkle",
        "Spark", "Comet", "Frost", "Rusty", "Sable", "Shadow", "Spark", "Spice", "Paws",
        "Whisker", "Clover", "Pebble", "Velvet", "Twig", "Cloud", "Maple", "Breeze", "Cinnamon",
        "Bubbles", "Muffin", "Ember", "Toffee", "Pebble", "Biscuit", "Sprout", "Rust", "Snickers",
        "Pearl", "Dapple", "Marble", "Puddle", "Pebbles", "Nutmeg", "Sable", "Tinsel", "Twinkle",
        "Ribbon", "Pecan", "Truffle", "Marshmallow", "Snickers", "Noodle", "Jelly", "Fudge",
        "Sprinkle", "Spark", "Comet", "Frost", "Rusty", "Sable", "Shadow", "Spark", "Spice",
        "Paws", "Whisker", "Clover", "Pebble", "Biscuit", "Pebble", "Rusty", "Marble", "Velvet",
        "Clover", "Paws", "Spark", "Shadow", "Sprout", "Whisker", "Twig", "Sable", "Pebbles",
        "Maple", "Cloud", "Ribbon", "Nutmeg", "Ember", "Toffee", "Pepper", "Frost", "Sparkle",
        "Muffin", "Jelly", "Fudge", "Bubbles", "Pebble", "Cinnamon", "Puddle", "Truffle", "Comet",
        "Snickers", "Marshmallow", "Dapple", "Spice", "Pecan", "Mocha", "Sprinkle", "Dusty",
        "Rust", "Pearl", "Dusk", "Sapphire", "Pippin", "Sprig", "Poppy", "Whistle", "Tinsel",
        "Oreo", "Pebble", "Breeze", "Muffin", "Velvet", "Paws", "Cloud", "Pebbles", "Ribbon",
        "Nutmeg", "Sprout", "Ember", "Fudge", "Pepper", "Spark", "Sable", "Maple", "Frost",
        "Biscuit", "Twinkle", "Snickers", "Toffee", "Jelly", "Marshmallow", "Shadow", "Pebble",
        "Rusty", "Marble", "Clover", "Sparkle", "Truffle", "Comet", "Pecan", "Dapple", "Spice",
        "Frost", "Mocha", "Sprinkle", "Dusty", "Pearl", "Dusk", "Sapphire", "Pippin", "Sprig",
        "Poppy", "Whistle", "Tinsel", "Oreo", "Velvet", "Pebble", "Breeze"
    };
    }
}
