-- MySQL Script generated by MySQL Workbench
-- Sun Mar 24 16:12:02 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema boredbets
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema boredbets
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `boredbets` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_hungarian_ci ;
USE `boredbets` ;

-- -----------------------------------------------------
-- Table `boredbets`.`jockey`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `boredbets`.`jockey` (
  `id` CHAR(36) NOT NULL,
  `name` VARCHAR(32) NULL DEFAULT NULL,
  `quality` INT NULL DEFAULT NULL,
  `country` VARCHAR(64) NULL DEFAULT NULL,
  `male` TINYINT(1) NULL DEFAULT NULL,
  `age` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_hungarian_ci;


-- -----------------------------------------------------
-- Table `boredbets`.`horses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `boredbets`.`horses` (
  `id` CHAR(36) NOT NULL,
  `name` VARCHAR(64) NULL DEFAULT NULL,
  `age` INT NULL DEFAULT NULL,
  `country` VARCHAR(64) NULL DEFAULT NULL,
  `stallion` TINYINT(1) NULL DEFAULT NULL,
  `jockey_id` CHAR(36) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_horses_jockey` (`jockey_id` ASC) VISIBLE,
  CONSTRAINT `fk_horses_jockey`
    FOREIGN KEY (`jockey_id`)
    REFERENCES `boredbets`.`jockey` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_hungarian_ci;


-- -----------------------------------------------------
-- Table `boredbets`.`tracks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `boredbets`.`tracks` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(124) NULL DEFAULT NULL,
  `country` VARCHAR(124) NULL DEFAULT NULL,
  `length` FLOAT NULL DEFAULT NULL,
  `address` VARCHAR(124) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 51
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_hungarian_ci;


-- -----------------------------------------------------
-- Table `boredbets`.`races`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `boredbets`.`races` (
  `id` CHAR(36) NOT NULL,
  `race_time` DOUBLE NOT NULL,
  `race_scheduled` DATETIME NOT NULL,
  `rain` TINYINT(1) NULL DEFAULT NULL,
  `track_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `track_id` (`track_id` ASC) VISIBLE,
  CONSTRAINT `track_id`
    FOREIGN KEY (`track_id`)
    REFERENCES `boredbets`.`tracks` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_hungarian_ci;


-- -----------------------------------------------------
-- Table `boredbets`.`participants`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `boredbets`.`participants` (
  `Id` CHAR(36) NOT NULL,
  `race_id` CHAR(36) NULL DEFAULT NULL,
  `horse_id` CHAR(36) NULL DEFAULT NULL,
  `placement` INT NULL DEFAULT NULL,
  PRIMARY KEY (`Id`),
  INDEX `horse_id` (`horse_id` ASC) VISIBLE,
  INDEX `race_id` (`race_id` ASC) VISIBLE,
  CONSTRAINT `participant_ibfk_1`
    FOREIGN KEY (`race_id`)
    REFERENCES `boredbets`.`races` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `participant_ibfk_2`
    FOREIGN KEY (`horse_id`)
    REFERENCES `boredbets`.`horses` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_hungarian_ci;


-- -----------------------------------------------------
-- Table `boredbets`.`transaction`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `boredbets`.`transaction` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `user_id` CHAR(36) NOT NULL,
  `deposit` INT NOT NULL DEFAULT '0',
  `bet` INT NOT NULL DEFAULT '0',
  `bet_outcome` INT NOT NULL DEFAULT '0',
  `created` DATETIME NOT NULL,
  PRIMARY KEY (`Id`),
  UNIQUE INDEX `Id_UNIQUE` (`Id` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_hungarian_ci;


-- -----------------------------------------------------
-- Table `boredbets`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `boredbets`.`users` (
  `id` CHAR(36) NOT NULL,
  `email` VARCHAR(255) NULL DEFAULT NULL,
  `password` VARCHAR(255) NULL DEFAULT NULL,
  `created` DATETIME(6) NULL DEFAULT NULL,
  `refresh_token` VARCHAR(255) NULL DEFAULT NULL,
  `admin` TINYINT(1) NULL DEFAULT NULL,
  `username` VARCHAR(20) NULL DEFAULT NULL,
  `wallet` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_hungarian_ci;


-- -----------------------------------------------------
-- Table `boredbets`.`user_bets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `boredbets`.`user_bets` (
  `Id` CHAR(36) NOT NULL,
  `user_id` CHAR(36) NOT NULL,
  `race_id` CHAR(36) NULL DEFAULT NULL,
  `horse_id` CHAR(36) NULL DEFAULT NULL,
  `bet_amount` INT NULL DEFAULT NULL,
  PRIMARY KEY (`Id`),
  INDEX `IX_user_bets_user_id` (`user_id` ASC) VISIBLE,
  INDEX `horse_id1` (`horse_id` ASC) VISIBLE,
  INDEX `race_id1` (`race_id` ASC) VISIBLE,
  CONSTRAINT `user_bets_ibfk_1`
    FOREIGN KEY (`race_id`)
    REFERENCES `boredbets`.`races` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `user_bets_ibfk_2`
    FOREIGN KEY (`horse_id`)
    REFERENCES `boredbets`.`horses` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `user_bets_ibfk_3`
    FOREIGN KEY (`user_id`)
    REFERENCES `boredbets`.`users` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_hungarian_ci;


-- -----------------------------------------------------
-- Table `boredbets`.`user_cards`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `boredbets`.`user_cards` (
  `creditcard_num` VARCHAR(20) NOT NULL,
  `cvc` VARCHAR(4) NOT NULL,
  `exp_year` VARCHAR(3) NOT NULL,
  `exp_month` VARCHAR(3) NOT NULL,
  `card_name` VARCHAR(25) NOT NULL DEFAULT 'CreditCard',
  `user_id` CHAR(36) NOT NULL,
  `card_holdername` VARCHAR(25) NULL DEFAULT NULL,
  PRIMARY KEY (`creditcard_num`),
  INDEX `IX_user_cards_user_id` (`user_id` ASC) VISIBLE,
  CONSTRAINT `user_cards_ibfk_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `boredbets`.`users` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_hungarian_ci;


-- -----------------------------------------------------
-- Table `boredbets`.`user_details`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `boredbets`.`user_details` (
  `user_id` CHAR(36) NOT NULL,
  `fullname` VARCHAR(255) NULL DEFAULT NULL,
  `address` VARCHAR(255) NULL DEFAULT NULL,
  `IsPrivate` TINYINT(1) NOT NULL,
  `birth_date` DATETIME(6) NULL DEFAULT NULL,
  PRIMARY KEY (`user_id`),
  CONSTRAINT `user_details_ibfk_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `boredbets`.`users` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_hungarian_ci;

USE `boredbets`;

DELIMITER $$
USE `boredbets`$$
CREATE
DEFINER=`boreDomDb`@`%`
TRIGGER `boredbets`.`after_delete_participant`
AFTER DELETE ON `boredbets`.`participants`
FOR EACH ROW
BEGIN
			
			DELETE FROM races WHERE id = OLD.race_id;
		END$$

USE `boredbets`$$
CREATE
DEFINER=`boreDomDb`@`%`
TRIGGER `boredbets`.`before_delete_participant`
BEFORE DELETE ON `boredbets`.`participants`
FOR EACH ROW
BEGIN
			
			DELETE FROM races WHERE id = OLD.race_id;
		END$$


DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
